/**
 * Supabase database types.
 *
 * This is a minimal placeholder generated by hand so the typed client compiles at
 * the scaffold stage. FEAT-002 introduces the real schema and will replace this
 * with the full generated `Database` type (via `supabase gen types typescript`).
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: Record<string, never>;
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
}
